name: Deployment website pribadi Ari jago

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build vite project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      
      - name: Build project
        run: npm run build
      
      - name: Coba nge log santuy
        run: echo "Deploying to Github Pages SANTUUYYYY"
      
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  coba:
    name: Coba aja buat nge log
    runs-on: ubuntu-latest
    steps:
      - name: Coba nge log santuy
        run: echo "Mantap!"

      - name: Ini step ke 2 coba nge log lagi
        run: echo "Ini step ke 2 coba nge log lagi"

  deploy:
      name: Deploy web nya Ari
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'

      steps:
        - name: Download artifact website Ari
          uses: actions/download-artifact@v2
          with:
            name: production-files
            path: ./dist
          
        - name: Deploy to Github pages web nya Ari
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist

        - name: Checkout ke gcloud Ari
          uses: actions/checkout@v4

        - name: Google Auth
          uses: google-github-actions/auth@v0
          with:
            credentials_json: ${{ secrets.GCP_SA_KEY }}
        
        - name: Setup Gcloud CLI
          uses: google-github-actions/setup-gcloud@v1
          with:
            service_account_email: ${{ secrets.GCP_SA_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}
            project_id: personal-website-413007
